# Generated by Django 4.2 on 2023-04-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filmname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('rating', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(upload_to='porters/')),
                ('video', models.FileField(upload_to='videos/')),
                ('views_count', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
