# Generated by Django 4.2.1 on 2023-07-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='production_country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
