# Generated by Django 4.2.1 on 2023-07-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_filmmodel_production_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='movie_duration',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
