# Generated by Django 4.2 on 2023-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_rename_filmname_filmmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('films', models.ManyToManyField(related_name='actor', to='film.filmmodel')),
            ],
        ),
    ]
