# Generated by Django 4.2.1 on 2023-07-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_filmmodel_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='actormodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors_photos'),
        ),
    ]
