# Generated by Django 4.2.1 on 2023-05-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_alter_commentmodel_options_likemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_likes', to='film.actormodel'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_likes', to='film.filmmodel'),
        ),
    ]
