# Generated by Django 4.2.1 on 2023-05-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='username',
            new_name='name',
        ),
    ]
